### ISSUE TITLE
Stolen code

### ISSUE THREAD

**Issue by mattman00000** [chauffer/SteamGame-util#27]
https://github.com/geekahedron/SteamGameAutoJoin/blob/master/autojoin.user.js

**Comment by chauffer** [comment]
The nature of open-source.

**Comment by geekahedron** [comment]
"Open source" does not mean "copy another person's code line-for-line and stick your name at the top."

**Comment by chauffer** [comment]
I only changed the line of the TamperMonkey/GreaseMonkey public line, I use this script, I link it to people, so I link them to my repo, as I know what code is in there.
It's a trust thing, don't take it personally.

**Comment by mattman00000** [comment]
You could fork it instead. That's the generally accepted way of doing things.

**Comment by chauffer** [comment]
This is a repo containing various files.
